[package]
name = "card_sorter"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.0.1"
tokio-serial = "5.4.1"
tokio = { version = "1.14.0", features = ["full"] }
ascii = "1.0.0"
log = "0.4.0"
env_logger = "0.8.4"
color-eyre = "0.5.11"
serde_json = "1.0"